# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20171214_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='funding',
            new_name='eventbrite_funds',
        ),
        migrations.AddField(
            model_name='team',
            name='corporate_funds',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
