# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20180110_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
